name: ECSS Backend Node

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:  
      contents: read  # This is required for actions/checkout
      id-token: write  # This is required for requesting the JWT
    environment:
      name: 'Production'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BCD0A2FBA9964706979486809F42DE29 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1FBDDC1349314EE598D02426BE106C4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61237747A91C44DAB298134C220B8DF7 }}

      - name: Set the correct Azure subscription
        run: |
          az account set --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61237747A91C44DAB298134C220B8DF7 }}

      - name: Set up Node.js version
        #if: ${{steps.check_changes.outputs.changes_detected == 'true' }}  
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        #if: ${{ steps.check_changes.outputs.changes_detected == 'true' }} 
        run: |
          cd backend
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Zip artifact for deployment (only backend folder)
        #if: ${{steps.check_changes.outputs.changes_detected == 'true' }}  
        run: |
          cd backend
          zip -r ../release.zip .  # Create zip file

      - name: Upload artifact for deployment
        #if: ${{ steps.check_changes.outputs.changes_detected == 'true' }} 
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: Deploy to Azure Web App (Linux)
        id: deploy-to-webapp
        #if: ${{ steps.check_changes.outputs.changes_detected == 'true' }} 
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecss-it-inventory-backend'
          slot-name: 'Production'
          package: ./release.zip  # Use the zip file created from the backend folder
          
      - name: Ensure deployment continues in background
        #if: ${{ steps.check_changes.outputs.changes_detected == 'true' }} 
        run: |
          echo "Deployment started. This will continue in the background."
